# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Liinn\Downloads\Agila\Agile-Development-Project-2025\project_root\src\gui\Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_menu_window(object):
    def setupUi(self, menu_window):
        menu_window.setObjectName("menu_window")
        menu_window.resize(1315, 857)
        font = QtGui.QFont()
        font.setPointSize(1)
        menu_window.setFont(font)
        menu_window.setMouseTracking(False)
        menu_window.setStyleSheet("background-color: rgb(209, 233, 246)")
        self.centralwidget = QtWidgets.QWidget(menu_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(775, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(166, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(500, 360))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\Liinn\\Downloads\\Agila\\Agile-Development-Project-2025\\project_root\\src\\gui\\resources/Logo_HabitTrack_NoText.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(165, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menu_button_register = QtWidgets.QPushButton(self.centralwidget)
        self.menu_button_register.setMinimumSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.menu_button_register.setFont(font)
        self.menu_button_register.setAutoFillBackground(False)
        self.menu_button_register.setStyleSheet("QPushButton{\n"
"background-color: rgb(174, 226, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"border-bottom: 6px solid;\n"
"border-top: 2px solid;\n"
"border-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:Pressed{\n"
"background-color: rgb(209, 233, 246);\n"
"border-bottom: 2px solid;\n"
"border-top: 6px solid;\n"
"border-color: rgb(255, 255, 255)\n"
"}")
        self.menu_button_register.setObjectName("menu_button_register")
        self.horizontalLayout_2.addWidget(self.menu_button_register)
        spacerItem9 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.menu_button_statistics = QtWidgets.QPushButton(self.centralwidget)
        self.menu_button_statistics.setMinimumSize(QtCore.QSize(150, 70))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.menu_button_statistics.setFont(font)
        self.menu_button_statistics.setStyleSheet("QPushButton{\n"
"background-color: rgb(174, 226, 255);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-style: solid;\n"
"border-width: 3px;\n"
"border-bottom: 6px solid;\n"
"border-top: 2px solid;\n"
"border-color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"QPushButton:Pressed{\n"
"background-color: rgb(209, 233, 246);\n"
"border-bottom: 2px solid;\n"
"border-top: 6px solid;\n"
"border-color: rgb(255, 255, 255)\n"
"}")
        self.menu_button_statistics.setDefault(False)
        self.menu_button_statistics.setFlat(False)
        self.menu_button_statistics.setObjectName("menu_button_statistics")
        self.horizontalLayout_2.addWidget(self.menu_button_statistics)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem11 = QtWidgets.QSpacerItem(20, 135, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        menu_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(menu_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1315, 26))
        self.menubar.setObjectName("menubar")
        menu_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(menu_window)
        self.statusbar.setObjectName("statusbar")
        menu_window.setStatusBar(self.statusbar)

        self.retranslateUi(menu_window)
        QtCore.QMetaObject.connectSlotsByName(menu_window)

    def retranslateUi(self, menu_window):
        _translate = QtCore.QCoreApplication.translate
        menu_window.setWindowTitle(_translate("menu_window", "HabitTrack"))
        self.label.setText(_translate("menu_window", "HabitTrack"))
        self.menu_button_register.setText(_translate("menu_window", "Register"))
        self.menu_button_statistics.setText(_translate("menu_window", "Statistics"))
