# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Liinn\Downloads\Agila\Agile-Development-Project-2025\project_root\src\gui\Registration_form_prototype.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


